server:
  port: 8080
  servlet:
    context-path: /
  shutdown: graceful  #默认immediate
  tomcat:
    mbeanregistry:
      enabled: true #监控tomcat相关指标
    accept-count: 1000 # 等待队列长度，默认100。
    max-connections: 5000 # 最大可被连接数，默认8192
    threads:
      max: 500 # 最大工作线程数，默认200,
      min-spare: 100 # 最小工作线程数，初始化分配线程数，默认10
    connection-timeout: 20000 #socket进入connection队列的最大时间


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  flyway:
    enabled: true
