server:
  port: 8082
  servlet:
    context-path: /normal
  shutdown: graceful  #默认immediate
  tomcat:
    mbeanregistry:
      enabled: true #监控tomcat相关指标
    accept-count: 200 # 等待队列长度，默认100。
    max-connections: 1000 # 最大可被连接数，默认8192
    threads:
      max: 500 # 最大工作线程数，默认200,
      min-spare: 100 # 最小工作线程数，初始化分配线程数，默认10
    connection-timeout: 20000 #socket进入connection队列的最大时间


spring:
  application:
    name: skill-normal
  shardingsphere:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 # 连接池初始化时创建的连接数
      min-idle: 5 # 连接池中保持的最小空闲连接数
      max-active: 20 # 连接池中允许的最大活动连接数
      max-wait: 60000 # 获取连接时的最大等待时间，超过此时间将抛出异常
      time-between-eviction-runs-millis: 60000 # 两次检查连接的时间间隔
      min-evictable-idle-time-millis: 300000 # 连接最小空闲时间，超过这个时间的连接将被回收
      remove-abandoned: true # 是否自动回收超时连接
      remove-abandoned-timeout-millis: 1800 # 自动回收超时连接的等待时间
      # 自己配置监控统计拦截的filter
      # https://www.cnblogs.com/jingzh/p/16216411.html
      filter:
        # 开启druiddatasource的状态监控
        stat:
          enabled: true
          db-type: mysql
          # 开启慢sql监控，超过2s 就认为是慢sql，记录到日志中
          log-slow-sql: true
          slow-sql-millis: 2000
        # 日志监控，使用slf4j 进行日志输出
        slf4j:
          enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      # 配置WebStatFilter，用于采集web关联监控的数据
      web-stat-filter:
        enabled: true                   # 启动 StatFilter
        url-pattern: /* # 过滤所有url
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # 排除一些不必要的url
        session-stat-enable: true       # 开启session统计功能
        session-stat-max-count: 1000 # session的最大个数,默认100
      # 配置StatViewServlet（监控页面），用于展示Druid的统计信息
      stat-view-servlet:
        enabled: true                   # 启用StatViewServlet
        url-pattern: /druid/* # 访问内置监控页面的路径，内置监控页面的首页是/druid/index.html
        reset-enable: false              # 不允许清空统计数据,重新计算
        login-username: root # 配置监控页面访问密码
        login-password: 123
        allow: 127.0.0.1 # 允许访问的地址，如果allow没有配置或者为空，则允许所有访问
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    password: 123456
    user: root
  data:
    redis:
      connect-timeout: 10s
      database: 1
      port: 6379
      host: localhost
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 8
          max-wait: 1000
    mongodb:
      uri: mongodb://localhost:27017/skill

